<?php
namespace tests\HelloPHPUnit;
use HelloPHPUnit\SayHello;

class HelloTest extends Base
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testValidateSayHelloReturnHello()
    {
        $this->assertEquals('Hallo!', SayHello::sayHallo());
    }
}
